# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 12:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grad_year', models.CharField(max_length=10)),
                ('cur_company', models.CharField(max_length=100, null=True)),
                ('prev_company', models.CharField(max_length=100, null=True)),
                ('projects', models.CharField(max_length=100, null=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
