# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 07:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='activities/%Y/%m/%d')),
                ('detail', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
