# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GIS', 'GIS'), ('GEGIS', 'GEGIS')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pastpapers')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('calculus_1', 'Calculus 1'), ('calculus_2', 'Calculus 2'), ('calculus_3', 'calculus 3'), ('calculus_4', 'calculus 4')], max_length=100)),
                ('code', models.CharField(choices=[('SMA 2270', 'SMA 2270'), ('EGS 2304', 'EGS 2304')], max_length=20)),
                ('course', models.ManyToManyField(to='pastpapers.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('year_1', 'Year 1'), ('year_2', 'Year 2'), ('year_3', 'Year 3'), ('year_4', 'Year 4'), ('year_5', 'Year 5')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastpapers.Unit'),
        ),
        migrations.AddField(
            model_name='paper',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastpapers.Year'),
        ),
    ]
