# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastpapers', '0002_auto_20170115_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='course',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='year',
        ),
        migrations.AddField(
            model_name='paper',
            name='course',
            field=models.CharField(choices=[('GIS', 'GIS'), ('GEGIS', 'GEGIS')], default='GIS', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
