# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastpapers', '0003_auto_20170119_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='slug',
            field=models.SlugField(default='calculus'),
            preserve_default=False,
        ),
    ]
