# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastpapers', '0005_auto_20170119_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='date',
            field=models.CharField(default='2015', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='unit_title',
            field=models.CharField(choices=[('Calculus I', 'Calculus 1'), ('Calculus II', 'Calculus 2'), ('Calculus III', 'calculus 3'), ('Calculus IV', 'calculus 4')], max_length=100),
        ),
    ]
