# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastpapers', '0006_auto_20170119_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=5),
            preserve_default=False,
        ),
    ]
